### ISSUE TITLE
Titlebar disappears during navigation

### ISSUE THREAD

**Issue by FodderMK** [zendesk/sdk_unity_plugin#72] opened 2018-04-02 17:17 UTC
I am attempting to get v1.11.2.1 of the plugin working with our game and came across a strange issue.  Everything works fine when I bring up the Help Center, but when I navigate to anything and then go back to the main menu the top navigation is gone.  For the screenshots attached, the first is when Help Center is opened, the second is when I look at my tickets, and the third is after hitting the back arrow on the tickets page.  I also see that the Android status bar disappears when navigating back to the main page.  Finally, even though the navigation is gone from the main page all subpages continue to work.  It is only the main menu that breaks.

![device-2018-04-02-100602](https://user-images.githubusercontent.com/1096012/38206242-894b24d8-365e-11e8-8ef6-55b21ac610a1.png)

![device-2018-04-02-100631](https://user-images.githubusercontent.com/1096012/38206245-8d1cc774-365e-11e8-8ef0-249dd0b1b1eb.png)

![device-2018-04-02-100640](https://user-images.githubusercontent.com/1096012/38206255-938f46cc-365e-11e8-929c-dfd9dfd9b01c.png)

**Comment by FodderMK** [comment] 2018-04-02 20:30
I neglected to mention that I'm building on Unity 2017.3.1.  I just noticed that the README only makes mention of Unity 5.x, does this mean 2017 is not supported?

**Comment by brendan-fahy** [comment] 2018-04-10 12:11
Hey @FodderMK, Unity 5.x was the latest major release the last time any significant work was done on this repo, which is why the README only mentions Unity 5.x. 

I just tested on Unity 2017.4.0f1, on a Nexus 5.x (Android 8.1) and a OnePlus One (Android 6.0), and I can't reproduce this issue. Can you give us any more detail that could help us to reproduce this? What devices/OS did you see this on? Have you been trying iOS as well, or just Android? 
From your screenshot it looks like the Toolbar is disappearing, and even the status bar. This could be some weird Unity stuff.

**Comment by baz8080** [comment] 2018-04-27 14:48
Going to close this issue because it's been a while, and we cannot reproduce it. If you need more help please get back in touch.

**Closed as completed by baz8080** 2018-04-27 14:48 UTC
Labels: pending information
